version: '3'

services:
  flask-api:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Vidwan
      POSTGRES_DB: mini-project

  frontend:
    build: .  
    ports:
      - "3000:3000"
